name: ebpf-trace
on:
  push:
    branches: [main]
  workflow_dispatch:
    
jobs:
  trace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run eBPF monitor
        uses: ./.github/actions/ebpf-monitor
      
      - name: Some Activity
        run: |
          curl -s https://www.google.com > /dev/null
          whoami
          ls -la /tmp
          python3 -c "print('Hello from Python')"

      - name: stop and trace coolect
        if: always()
        run: |
          sudo pkill -INT bpftrace || true
          sleep 2

          cat /tmp/ebpf_trace.log
